# Generated by Django 3.1.7 on 2021-03-25 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210325_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date rendez_vous'),
            preserve_default=False,
        ),
    ]
