# Generated by Django 3.1.7 on 2021-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(verbose_name='date_rendez_vous'),
        ),
    ]
